#!/usr/bin/env bash

# Runs phpunit for both internal and external php-fpm

printf "\033[44mRunning phpunit for ragu-php-fpm-external\033[0m\n"
docker exec -it ragu-php-fpm-external bin/phpunit "$@"
printf "\033[44mRunning phpunit for ragu-php-fpm-internal\033[0m\n"
docker exec -it ragu-php-fpm-internal bin/phpunit "$@"